# https://developer.1password.com/docs/ssh/agent/config
[[ssh-keys]]
vault = "Shared"
item = "Personal GitHub SSH Key"

[[ssh-keys]]
vault = "Shared"
item = "Raspberry Pi SSH Key"

[[ssh-keys]]
vault = "Pillar Software Lab"
item = "Fxdigital-ssh"
